# This action was adapted from "Sebastián Ramírez <tiangolo@gmail.com>"
# From the FastAPI project.
# See for more details:
# https://github.com/tiangolo/fastapi/tree/master/github/actions/people
name: "Generate LangChain People"
description: "Generate the data for the LangChain People pages"
inputs:
  token:
    description: 'User token, to read the GitHub API. Can be passed in using {{ secrets.LANGCHAIN_PEOPLE }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
