name: Check Imports

on:
  push:
    branches:
      - main  # or replace 'main' with the name of your default branch

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run import check
      run: |
        git grep 'from langchain import' | grep -vE 'from langchain import (__version__)' && exit 1 || exit 0
