---
name: libs/langchain Release

on:
  pull_request:
    paths:
      - 'libs/langchain/**'
      - 'libs/langchain/pyproject.toml'

jobs:
  release:
    uses:
      ./.github/workflows/_release.yml
    with:
      working-directory: libs/langchain
    secrets: inherit