---
name: libs/langchain Lint

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - '.github/workflows/_lint.yml'
      - '.github/workflows/langchain_lint.yml'
      - 'libs/langchain/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-libs-fancy:
    uses:
      ./.github/workflows/_lint.yml
    with:
      working-directory: libs/langchain
    secrets: inherit